### ISSUE TITLE
"Expand upon 2 use cases and their scenarios"

### ISSUE THREAD

**Issue by hd2802** [hd2802/Dungeon-Delver#26]
Section of the Deliverable 2 Report.

This section requires a thumbs up reaction from 3 or more members in order to be approved for the final report. 

Feel free to add any comments on here or on the Google Docs 

https://docs.google.com/document/d/1RfQzcOe1-nD_XuqAVp3PO_yAmeJ5h7QeSdVjSvPILLs/edit

**Comment by hd2802** [comment]
A fundamental use case is a D&D player who understands how the game works - and thus is not looking for a tutorial like the new player - but instead wants a tool to aid them with various things in the game - such as creating a character sheet, rolling dice and even tracking game sessions.

The character sheet determines what your character can and cannot do easily. It contains information regarding the characters core statistics (out of strength, dexterity, constitution, wisdom, intelligence and charisma) and what skills that they excel in. There is a formal set of rules that determine all of the above and the website would ideally support the user in sticking to these rules. The website would also ideally automate some processes that are required in creating a character sheet, that would be cumbersome to do by hand. 

The D&D player would also be able to track games and sessions using the website. As the website should implement a log-in feature, the player could become friends with the people that they are in D&D parties with and there would include a scheduling system and a way to track campaigns in the website. 

Another fundamental use case is an aspiring D&D player looking for an interactive and rewarding way to learn how the game works. 

The website would first encourage the new player to partake in an interactive mini campaign - designed to introduce the player to core mechanics such as roleplaying, dice rolling and combat. This would ideally teach the new player how the game works in a way that is interactive and engaging. 

The website would then sign post the new player to various features that the site offers that would aid them in setting up for a first game - including creating a character sheet and finding a group to play with.

**Comment by ruilin23** [comment]
Use case 1: Interactive Character Creation Tool

User Profile: A new player with none or minimal experience in D&D

Problem: The user finds the character creation process overwhelming and convoluted due to the vast number of choices and rules involved

Solution: Offer an interactive character creation tool which simplifies the process by providing a step-by-step guide with simplistic explanations and recommendations based on the user’s preferences and character’s intended role.

Process:
The user chooses to begin a new character creation process
The tool asks a series of questions regarding the desired character such as the user’s preferred playstyle, desired role and the archetypes they prefer
Based on the user’s answers, the tool suggests relevant races, classes and backgrounds that most closely fit the user’s answers.
The tool then guides the user thought the process of customizing their character, giving useful tips and information relating to things such as ability scores, skills and equipment they should use
Finally, the tool generates a character sheet for the user that can be saved for later usage in games

Use case 2: Interactive Trial Campaign

User Profile: A group of new players and a novice Dungeon Master(DM)

Problem: The group is unsure on how to start playing D&D and not very familiar with the game mechanics

Solution: Provide an interactive trial campaign designed specifically for new players and relatively new DMs. This trial campaign would be shorter and simpler than standard ones, focusing on teaching the basic mechanics of the game. 

Process:
The DM accesses the trial campaign 
The campaign starts with a brief tutorial, explaining the basic rules and role of the DM and players to the group
The campaign is structured to slowly and gradually introduce gameplay mechanics to the group. (This includes; combat, skill checks and role-playing encounters) This should be done in a slow and guided environment in case of group uncertainty. Users would be given the chance to expand on explanations for more detailed ones.
Throughout the playthrough of the campaign, tips and hints will be provided by the website to aid the DM in storytelling and assisting players to better understand their options.
Once the campaign has concluded, a summary of what should have been learnt will be provided along with suggestions for future adventures.
